#include<bits/stdc++.h>
#define int long long
using namespace std;
int T,n,i,j,a[100009],b[100009],vis[400009],zhi,jud[800009];
int anss,ans[400009],flag[400009];
bool ff;
signed main(){
	freopen("5.in","r",stdin);freopen("5.out","w",stdout);
	cin>>T;
	for(i=2;i<=400000;i++){
		if(flag[i]==0){
			ans[++anss]=i;//记录下来 
		}
		for(j=1;j<=anss&&i*ans[j]<=400000;j++){
			flag[ans[j]*i]=1;//一下子筛到底 
			//当然，i肯定比ans[j]大，因为ans[j]是在i之前得出的
			if(i%ans[j]==0)break;
		}
	}
	while(T--){
		scanf("%lld",&n);ff=0;zhi=0;
		for(i=1;i<=n;i++){
			scanf("%lld",&a[i]);
			vis[a[i]]=1;
		}
		for(i=1;i<=n;i++){
			if(flag[a[i]]==0){
				if(zhi>0){
					ff=1;
					break;
				}
				else zhi=a[i];
			}
		}
		if(ff==1){
			printf("-1\n");
			continue;
		}
		if(zhi==0){
			printf("2\n");
			continue;
		}
		else{
			jud[zhi*2]=1;
			for(i=zhi*2;i<=min(zhi*2+30,400000ll);i++){
				if(jud[i]==1){
					for(j=2;j*j<=i;j++){
						if(i%j==0){
							jud[i+j]=1;
							jud[i+i/j]=1;
						}
					}
				}
			}
			for(i=1;i<=n;i++){
				if(a[i]<zhi){
					ff=1;
					break;
				}
				if(a[i]>zhi&&a[i]<zhi*2){
					ff=1;
					break;
				}
				if(a[i]==zhi*2+1){
					ff=1;
					break;
				}
				if(zhi!=3&&a[i]==zhi*2+3){
					ff=1;
					break;
				}
				if((zhi*2+2)%3!=0&&a[i]==(zhi*2+5)){
					ff=1;
					break;
				}
				if(jud[a[i]]==1){
					continue;
				}
				if(jud[a[i]]==0&&a[i]>=zhi*2&&a[i]<=zhi*2+30&&zhi<=1000){
					ff=1;
					break;
				}
				if(jud[a[i]]==0&&a[i]>=zhi*2&&a[i]<=zhi*2+150&&zhi>=10000){
					ff=1;
					break;
				}
			}
			if(ff==1)printf("-1\n");
			else printf("%lld\n",zhi);
			for(i=min(zhi*2+50,400000ll);i>=zhi*2;i--){
				if(jud[i]==1){
					jud[i]=0;
					for(j=2;j*j<=i;j++){
						if(i%j==0){
							jud[i+j]=0;
							jud[i+i/j]=0;
						}
					}
				}
			}
		}
		for(i=1;i<=n;i++){
			vis[a[i]]=0;
		}
	}
	fclose(stdin);fclose(stdout);
	return 0;
}
